site_name: RayforceDB
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.html
  - Getting Started:
    - Installation: content/getstarted/index.html
  - Reference:
    - Syntax: content/syntax.html
    - Functions: content/reference.html
    - Atomic Operations: content/atomic.html
    - FAQ: content/faq.html
  - Components:
    - Time: content/time/index.html
    - Update: content/update/index.html
    - Temporal: content/temporal/index.html
    - REPL: content/repl/index.html
    - Serialization: content/serde/index.html
    - Order: content/order/index.html
    - Query: content/query/index.html
    - Math: content/math/index.html
    - Join: content/join/index.html
    - Logic: content/logic/index.html
    - Iteration: content/iter/index.html
    - Items: content/items/index.html
    - IO: content/io/index.html
    - Interfacing: content/interfacing/index.html
    - Format: content/format/index.html
    - Environment: content/env/index.html
    - Composition: content/compose/index.html
    - Comparison: content/cmp/index.html
  - Benchmarks: content/benchmarks/index.html
  - License: content/license.html 