site_name: RayforceDB
repo_url: https://github.com/singaraiona/rayforce
repo_name: GitHub

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github 
  logo: images/logo_light_full.svg
  favicon: images/favicon.svg
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom     # Rayforce golden
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom     # Rayforce golden
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Outfit
    code: JetBrains Mono

  icon:
    logo: material/lumx


extra:
    social:
      - icon: fontawesome/brands/github 
        link: https://github.com/singaraiona
      - icon: fontawesome/brands/x-twitter
        link: https://x.com/RayforceDB
      - icon: fontawesome/brands/reddit
        link: https://www.reddit.com/r/rayforcedb/
      - icon: simple/zulip
        link: https://rayforcedb.zulipchat.com/#narrow/channel/549008-Discuss
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/anton-kundenko-a22a3667
      - icon: fontawesome/solid/paper-plane
        link: mailto:<singaraiona@gmail.com>

copyright: Copyright &copy; 2023 RayforceDB

plugins:
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes

extra_css:
  - https://adobe-fonts.github.io/source-code-pro/source-code-pro.css
  - https://cdnjs.cloudflare.com/ajax/libs/asciinema-player/2.6.1/asciinema-player.css
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/asciinema-player/2.6.1/asciinema-player.js
  
# Page tree
nav:
  - Home: index.md

  - Get Started:
    - Overview: content/get-started/overview.md
    - Install: content/get-started/install.md
    - Benchmarks:
      - Overview: content/get-started/benchmarks/overview.md
      - Group By: content/get-started/benchmarks/group-by.md
      - Inner Join: content/get-started/benchmarks/inner-join.md
      - Left Join: content/get-started/benchmarks/left-join.md
      - Window Join: content/get-started/benchmarks/window-join.md
    - Technical Details: content/get-started/technical-details.md
    - Contribute: content/get-started/contribute.md

  - Documentation:
    - Overview: content/documentation/overview.md
    - Data Types:
      - Overview: content/documentation/data-types/overview.md
      - Integers: content/documentation/data-types/integers.md
      - Float: content/documentation/data-types/float.md
      - Temporal: content/documentation/data-types/temporal.md
      - Symbol: content/documentation/data-types/symbol.md
      - String: content/documentation/data-types/string.md
      - Char: content/documentation/data-types/char.md
      - GUID: content/documentation/data-types/guid.md
      - Boolean: content/documentation/data-types/boolean.md
      - Enum: content/documentation/data-types/enum.md
      - Vector: content/documentation/data-types/vector.md
      - List: content/documentation/data-types/list.md
      - Table: content/documentation/data-types/table.md
      - Dictionary: content/documentation/data-types/dictionary.md
      - Functions: content/documentation/data-types/functions.md
      - Other: content/documentation/data-types/other.md
    - Queries:
      - Overview: content/documentation/queries/overview.md
      - Select: content/documentation/queries/select.md
      - Update: content/documentation/queries/update.md
      - Insert: content/documentation/queries/insert.md
      - Upsert: content/documentation/queries/upsert.md
      - Alter: content/documentation/queries/alter.md
      - Joins: content/documentation/queries/joins.md
    - Operations:
      - Overview: content/documentation/operations/overview.md
      - Math: content/documentation/operations/math.md
      - Order: content/documentation/operations/order.md
      - Logic: content/documentation/operations/logic.md
      - Iterable: content/documentation/operations/iterable.md
      - Compose: content/documentation/operations/compose.md
      - Evaluation Control: content/documentation/operations/evaluation-control.md
      - IO: content/documentation/operations/IO.md
    - Environment: content/documentation/environment.md
    - Format: content/documentation/format.md
    - Serialization: content/documentation/serialization.md
    - IPC: content/documentation/IPC.md
    - REPL: content/documentation/REPL.md
    - Misc: content/documentation/misc.md

  - FAQ: content/faq.md

  - License: content/license.md
