name: Build and Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Upload RELEASE.md
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: RELEASE.md  

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y build-essential

    - name: Make (Linux)
      if: runner.os == 'Linux'
      run: make CC="gcc" release

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install make -y

    - name: Get gcc (Windows)
      if: runner.os == 'Windows'
      run: Invoke-WebRequest -Uri "https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r2.zip" -OutFile "mingw.zip"
        
    - name: Install gcc (Windows)
      if: runner.os == 'Windows'
      run: Expand-Archive -Path mingw.zip
        
    # $env:Path = "${{ github.workspace }}/mingw/bin;" + $env:Path

    - name: Make (Windows)
      if: runner.os == 'Windows'
      run: mingw32-make.exe CC="${{ github.workspace }}/mingw/bin/gcc" release 
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        if ! command -v clang &> /dev/null
        then
          xcode-select --install
        fi

    - name: Make (macOS)
      if: runner.os == 'macOS'
      run: make release

    - name: Create build directory and copy binary (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cd build
        zip -r ../${{ matrix.os }}.zip .  

    - name: Create build directory and copy binary (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir build
        cp ./rayforce.exe ./build/
        cd build
        7z a ../${{ matrix.os }}.zip .

    - name: Create build directory and copy binary (macOS)
      if: runner.os == 'macOS'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cd build
        zip -r ../${{ matrix.os }}.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}.zip
        path: ${{ matrix.os }}.zip
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: ${{ github.workspace }}/release-notes/RELEASE.md
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/ubuntu-latest.zip/ubuntu-latest.zip
        asset_name: linux.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/windows-latest.zip/windows-latest.zip
        asset_name: windows.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/macos-latest.zip/macos-latest.zip
        asset_name: macos.zip
        asset_content_type: application/zip
