name: Build and Release

on:
  push:
    tags:
      - 'v*.*'
      - 'nightly'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Upload RELEASE.md
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: RELEASE.md  

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y build-essential

    - name: Make (Linux)
      if: runner.os == 'Linux'
      run: make CC="gcc" RELEASE_CFLAGS="-fPIC -Wall -Wextra -std=c17 -Ofast -march=x86-64 -msse -msse2 -mavx -mavx2 -fassociative-math -ftree-vectorize -m64" release

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install make -y

    - name: Install gcc (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r2.zip" -OutFile "${{ github.workspace }}/mingw.zip" -Verbose
        Expand-Archive -Path ${{ github.workspace }}/mingw.zip -DestinationPath ${{ github.workspace }}/mingw -Verbose

    - name: Make (Windows)
      if: runner.os == 'Windows'
      run: |
        mingw32-make.exe LFLAGS="" CC="${{ github.workspace }}/mingw/mingw64/bin/gcc" AR="${{ github.workspace }}/mingw/mingw64/bin/ar" RELEASE_CFLAGS="-fPIC -Wall -Wextra -std=c17 -Ofast -march=x86-64 -msse -msse2 -mavx -mavx2 -fassociative-math -ftree-vectorize -m64" LIBS="-lm -lws2_32 -lkernel32" release
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        if ! command -v clang &> /dev/null
        then
          xcode-select --install
        fi

    - name: Make (macOS)
      if: runner.os == 'macOS'
      run: make RELEASE_CFLAGS="-fPIC -Wall -Wextra -std=c17 -Ofast -march=x86-64 -msse -msse2 -mavx -mavx2 -fassociative-math -ftree-vectorize -m64" release

    - name: Create build directory and copy binary (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cp -r ./examples ./build/
        cd ./build
        tar -cvpzf ../${{ matrix.os }}.tar.gz *

    - name: Create build directory and copy binary (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir build
        cp ./rayforce.exe ./build/
        cp ${{ github.workspace }}/mingw/mingw64/bin/libmcfgthread-1.dll ./build/
        cp -r ./examples ./build/
        cd build
        7z a ../${{ matrix.os }}.zip .

    - name: Create build directory and copy binary (macOS)
      if: runner.os == 'macOS'
      run: |
        mkdir build
        cp ./rayforce ./build/
        cp -r ./examples ./build/
        cd ./build
        tar -cvpzf ../${{ matrix.os }}.tar.gz *

    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v4
      if: runner.os == 'Linux'
      with:
        name: ${{ matrix.os }}.tar.gz
        path: ${{ matrix.os }}.tar.gz

    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v4
      if: runner.os == 'Windows'
      with:
        name: ${{ matrix.os }}.zip
        path: ${{ matrix.os }}.zip

    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v4
      if: runner.os == 'macOS'
      with:
        name: ${{ matrix.os }}.tar.gz
        path: ${{ matrix.os }}.tar.gz
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
  
      - name: Create Release and Upload Assets
        run: |
          gh release create ${{ github.ref }} \
            --repo ${{ github.repository }} \
            --title ${{ github.ref }} \
            --notes-file ${{ github.workspace }}/release-notes/RELEASE.md \
            --draft=false \
            --prerelease=false \
            ${{ github.workspace }}/ubuntu-latest.tar.gz/ubuntu-latest.tar.gz \
            ${{ github.workspace }}/windows-latest.zip/windows-latest.zip \
            ${{ github.workspace }}/macos-latest.tar.gz/macos-latest.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        